map_memory_node:
  ros__parameters:
    frame_id: "sim_world"
    resolution: 0.1
    width: 40.0
    height: 40.0
    origin_x: -20.0
    origin_y: -20.0
    update_distance: 1.5
    update_period: 1.0
